language: java

notifications:
  email: false

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli
  - cd ../backend/
  - ./gradlew build -x test

deploy:
  provider: heroku
  api_key:
    secure: CDE5qx/sNZMohX6969rr2DqCaEHr9wVFndB5MPOiRZsK3pe8KEunhg6SzW4AGFjG5HaPwicTCc8J0mb4j1GQrkl8LZopF2TYoLBxz6rsZrk5eOa5CcnpaXXJM/p1U+rfwUjZuJogWJmPvWjkwzAwuMqwbKe2zuaI469Cf//wCK0YLO3C43MMhOMxfiTzEYEtHM/LYiQSfFbm6fGWUsv8eqty8Ms45klJSkK0c8YC7+e8NpsWKKCqa10yE90ZM3v1d6pexrLZnXTXth+/6f8AZuIvBZDLjkR4iqcN6GckXSs37nDemb3PTiWraJB/o9weuHs02ETvrp3Sy1QEsGLx69qmlgMiCsGUuRnMWllO+67Xvaj/j/mZRFfIFEk+u5LlSOy73874PQ2JqimLrF2Qu4cNRlBoCzP6/L3KIwYj+W4oi1Rl96eKOQGKiuaFEQSkZz/iZxRMDCvi07wOfaEYsezWHFmvnxbMWnB4j43u/Izo7Ys0wCy1+8p6K//0yQWkY9pyst1nz2FJ/g+klUfphArJ6b7FzDXfZqJmjwEmQTBLtVb/A+6i3rE/fnhsRreUmrI6CU62bnM/8J29I/Qg6LW/W8gDJsvioN6YpGKGjKA0DWhMEQFbCUBsw6FvIbUaYpaCyZrxbFGqZpkVEtsedW8SVFPs/c4CkLNmF6AiY88=
  app: projet-java
  skip_cleanup: true
  on:
    branch:
      master
